ccflags-$(CONFIG_ARCH_MSM) += -DBSP_SIL_PLAT_QCOM
ccflags-$(CONFIG_ARCH_QCOM) += -DBSP_SIL_PLAT_QCOM
ccflags-$(CONFIG_ARCH_SPRD) += -DBSP_SIL_PLAT_SPRD
silead_fps_mmi-y += silead_fp.o
obj-$(CONFIG_INPUT_SILEAD_FPS_MMI) += silead_fps_mmi.o
