obj-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2) += focaltech_0flash_v2_mmi.o

ccflags-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2_ENABLE_DOUBLE_TAP) += -DFOCALTECH_SENSOR_EN
ccflags-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2_NOTIFY_TOUCH_STATE) += -DFTS_SET_TOUCH_STATE
ccflags-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2_ESD_EN) += -DFOCALTECH_ESD_EN
ccflags-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2_PANEL_NOTIFICATIONS) += -DFOCALTECH_CONFIG_PANEL_NOTIFICATIONS
ccflags-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2_DEBUG_EN) += -DFOCALTECH_DEBUG_EN
ccflags-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2_IC_NAME_FT8057) += -DCONFIG_INPUT_FOCALTECH_0FLASH_MMI_IC_NAME_FT8057
ccflags-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2_PINCTRL_EN) += -DFOCALTECH_PINCTRL_EN
ccflags-$(CONFIG_TOUCHSCREEN_FTS_0FLASH_MMI_V2_LAST_TIME) += -DFTS_LAST_TIME_EN

focaltech_0flash_v2_mmi-objs += focaltech_core.o
focaltech_0flash_v2_mmi-objs += focaltech_esdcheck.o
focaltech_0flash_v2_mmi-objs += focaltech_ex_fun.o
focaltech_0flash_v2_mmi-objs += focaltech_ex_mode.o
focaltech_0flash_v2_mmi-objs += focaltech_flash.o
focaltech_0flash_v2_mmi-objs += focaltech_gesture.o
focaltech_0flash_v2_mmi-objs += focaltech_point_report_check.o
focaltech_0flash_v2_mmi-objs += focaltech_spi.o
